# Generated by Django 5.1.4 on 2024-12-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_event_id_alter_eventmember_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
